### ISSUE TITLE
Probable bug: the app crashes as soon as you log in to Piped

### ISSUE THREAD

**Issue by 25huizengek1** [25huizengek1/ViMusic#39]
Moving this bug report to a separate issue @siggi1984

---

I use kavin.rocks

Unfortunately I have no idea how to create these logs.

At the moment I can't even select an instance. See video.

My device: Samsung Galaxy a21s, Android 12.

https://github.com/25huizengek1/ViMusic/assets/103368536/65a40479-7a60-4d6a-a1a5-2fc1c6f92781

_Originally posted by @siggi1984 in https://github.com/25huizengek1/ViMusic/issues/2#issuecomment-1853293969_

---
            
No logs provided (yet). Unfortunately cannot reproduce.

The instance list not working is not a problem on my end: the [instance list](https://piped-instances.kavin.rocks/) is currently not reachable ([partial downtime](https://status.piped.video/)).

Side note: video resolving can be inconsistent right now, as ViMusic relies on whatever.social to resolve more possible video/audio streams to make more songs available on ViMusic. Since [whatever.social is currently down (status)](https://status.piped.video/incident/12208), this can be an inconvenience. If you have listened to a song before, this won't impact you for that particular song, but other songs that you've never listened to may be unavailable now.

Thank you for reporting this @siggi1984

**Comment by Enigma1309** [comment]
Yep it's a confirmed bug .

**Comment by 25huizengek1** [comment]
I still cannot reproduce this. The instances list is not available / down, so that explains why you cannot login right now.

I can probably change this behaviour so that the custom instance is still usable, but it is not a bug / crash. (can't reproduce)

**Comment by 25huizengek1** [comment]
I'm still able to log in perfectly fine without any crashes at all. I did polish the implementation a bit more though: 2bc407d3d9a74163c3ecbaa5d9bb97648b182bd0

**Comment by siggi1984** [comment]
> I'm still able to log in perfectly fine without any crashes at all. I did polish the implementation a bit more though: [2bc407d](https://github.com/25huizengek1/ViMusic/commit/2bc407d3d9a74163c3ecbaa5d9bb97648b182bd0)

It still doesn't work for me (I can't log in) but maybe with the next version. I will have a look as soon as they have released it.

**Comment by 25huizengek1** [comment]
I think this has to do with the downtime. Have you had any crashes though?

**Comment by Enigma1309** [comment]
In my case it doesn't seem to fetch servers and always shows the error

https://github.com/25huizengek1/ViMusic/assets/94917588/5474ca20-aa1b-4fb0-ac92-9c4e2f01c19e

**Comment by siggi1984** [comment]
> I think this has to do with the downtime. Have you had any crashes though?

Logging in is now a problem but as soon as I start typing playlists, the app crashes, see video.


https://github.com/25huizengek1/ViMusic/assets/103368536/0f56e1ad-2002-45bf-85d8-8d560d0336d2

**Comment by 25huizengek1** [comment]
> In my case it doesn't seem to fetch servers and always shows the error
> 
> https://github.com/25huizengek1/ViMusic/assets/94917588/5474ca20-aa1b-4fb0-ac92-9c4e2f01c19e
> 
> 

Was aware, instance list was down...

**Comment by 25huizengek1** [comment]
> > I think this has to do with the downtime. Have you had any crashes though?
> 
> Logging in now works but as soon as I go to playlist the app crashes, see video.
> 
> 
> https://github.com/25huizengek1/ViMusic/assets/103368536/0f56e1ad-2002-45bf-85d8-8d560d0336d2
> 
> 

Very strange, it should not crash. I'll look into this later.

**Comment by 25huizengek1** [comment]
I can't reproduce the crash unfortunately, so maybe I make some assumptions in my code that I shouldn't have made. To debug this, I'll really need some logs from you to investigate. Please use the most recent nightly build, or provide the date of the nightly build together with the logs. To capture logs, you can use `adb logcat`, or, if you have root access on your device or installed [Shizuku](https://shizuku.rikka.app/), you can use something like https://github.com/F0x1d/LogFox to 'record' logs. Please filter on the `it.vfsfitvnm.vimusic.nightly` to unclutter the logs a bit, if you can.

**Comment by siggi1984** [comment]
> I can't reproduce the crash unfortunately, so maybe I make some assumptions in my code that I shouldn't have made. To debug this, I'll really need some logs from you to investigate. Please use the most recent nightly build, or provide the date of the nightly build together with the logs. To capture logs, you can use `adb logcat`, or, if you have root access on your device or installed [Shizuku](https://shizuku.rikka.app/), you can use something like https://github.com/F0x1d/LogFox to 'record' logs. Please filter on the `it.vfsfitvnm.vimusic.nightly` to unclutter the logs a bit, if you can.

FATAL EXCEPTION: main
Process: it.vfsfitvnm.vimusic.nightly, PID: 23243
java.lang.IllegalArgumentException: Key "piped-1" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at g0.C.H(SourceFile:175)
	at v.C.a(SourceFile:34)
	at u.E.a(SourceFile:21)
	at u.y.b(SourceFile:52)
	at u.z.c0(SourceFile:714)
	at p.P.c0(SourceFile:342)
	at g0.E.c(SourceFile:88)
	at i0.w.a(SourceFile:41)
	at o.m.a(SourceFile:19)
	at o.m.a0(SourceFile:14)
	at g0.z.c(SourceFile:13)
	at i0.B.a(SourceFile:11)
	at o.m.a(SourceFile:55)
	at o.m.a0(SourceFile:27)
	at g0.z.c(SourceFile:13)
	at i0.B.a(SourceFile:11)
	at T.N.c(SourceFile:6)
	at i0.B.a(SourceFile:11)
	at s.H.c(SourceFile:104)
	at i0.B.a(SourceFile:11)
	at i0.J.a(SourceFile:14)
	at i0.J.p(SourceFile:8)
	at D.j.e(SourceFile:65)
	at M.A.a(SourceFile:60)
	at i0.o0.a(SourceFile:71)
	at i0.M.o0(SourceFile:107)
	at i0.T.c(SourceFile:55)
	at i0.T.j(SourceFile:110)
	at i0.T.f(SourceFile:101)
	at androidx.compose.ui.platform.AndroidComposeView.w(SourceFile:34)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:22)
	at android.view.View.draw(View.java:23901)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:602)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:608)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:684)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5440)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5148)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4212)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10491)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)



I hope I have done it right and it helps further with the error search.

**Comment by 25huizengek1** [comment]
Thank you so much, don't even have to map the logs, I can see why it crashes (naive LazyGrid keys, my fault)

Dang it, my first crash! 😂 

Fixed it, please reopen if there are any issues with tomorrow's build.

**Comment by siggi1984** [comment]
In the latest nightly version, the app no longer crashes.

But there is still a small flaw, the song covers and playlist covers are not loaded.
See screenshot.
![Screenshot_20231215-171306](https://github.com/25huizengek1/ViMusic/assets/103368536/05488ac1-e099-414c-aeeb-6ff4233bf5ef)
![Screenshot_20231215-171148](https://github.com/25huizengek1/ViMusic/assets/103368536/99a37b8b-94f7-490e-8357-60dd6ac2861b)

**Comment by 25huizengek1** [comment]
I know, kavin.rocks is behind Cloudflare protection, so the app can't load the images. As far as I'm aware I cannot (legally) bypass it, so the only thing I can do is maybe add a warning for Cloudflare protected instances.

**Comment by siggi1984** [comment]
Would it be possible to create new piped playlists with ViMusic and also edit them, for example adding new songs or removing songs from the playlist?
