### ISSUE TITLE
App crashes when swiping away the mini-player

### ISSUE THREAD

**Issue by Syntax-Err5** [25huizengek1/ViMusic#41]
### Steps to reproduce the bug

1. Play any song
2. Minimise and close the player (to clear queue)

### Expected behavior

Queue is cleared and song stops playing

### Actual behavior

App crashes

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViMusic/assets/123362106/229e5609-e147-416c-8c1f-6a432c5b5ae0

### Logs

FATAL EXCEPTION: main
Process: it.vfsfitvnm.vimusic, PID: 13539
java.lang.NullPointerException: Attempt to read from field 'android.os.Bundle android.app.Notification.extras' on a null object reference in method 'void android.app.Notification.addFieldsFromContext(android.content.pm.ApplicationInfo, android.app.Notification)'
	at android.app.Notification.addFieldsFromContext(Notification.java:3429)
	at android.app.Notification.addFieldsFromContext(Notification.java:3422)
	at android.app.NotificationManager.fixNotification(NotificationManager.java:704)
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:695)
	at android.app.NotificationManager.notify(NotificationManager.java:644)
	at android.app.NotificationManager.notify(NotificationManager.java:620)
	at androidx.activity.d.run(SourceFile:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8377)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

### ViMusic version

0.5.11

### Android version

ColorOS 13, based on Android 13

**Comment by Enigma1309** [comment]
yes i was just going to make the same issue 👀

**Comment by 25huizengek1** [comment]
I’ll look into this later. Very strange, because on stock Android 13 it does not happen. Might be a platform inconsistency I did not expect.

**Comment by 25huizengek1** [comment]
I think I've fixed it, nightly build will start today in a few minutes, so you can test it immediately. Since I cannot reproduce the crash I cannot verify if it's fully fixed, but let me know if it is and reopen if there are any more issues.

**Comment by Syntax-Err5** [comment]
Ok so it works perfectly until I import my backup file from the 0.5.11 stable build. Could it be something wrong with the database? 🤷


I got this crash after importing the db:

FATAL EXCEPTION: main
Process: it.vfsfitvnm.vimusic.nightly, PID: 13736
java.lang.NullPointerException: Attempt to read from field 'android.os.Bundle android.app.Notification.extras' on a null object reference in method 'void android.app.Notification.addFieldsFromContext(android.content.pm.ApplicationInfo, android.app.Notification)'
	at android.app.Notification.addFieldsFromContext(Notification.java:3429)
	at android.app.Notification.addFieldsFromContext(Notification.java:3422)
	at android.app.NotificationManager.fixNotification(NotificationManager.java:704)
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:695)
	at android.app.NotificationManager.notify(NotificationManager.java:644)
	at android.app.NotificationManager.notify(NotificationManager.java:620)
	at B3.j.run(SourceFile:33)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8377)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)


It looks like it's all the same except for this line:
at B3.j.run(SourceFile:33)

**Comment by 25huizengek1** [comment]
Another edge case maybe, reopened, will look into it later

**Comment by 25huizengek1** [comment]
I hope I fixed it in b6bf32a1bcde2fb960d7948b9217c5c190c86acd but not quite sure. The NotificationManager calls shouldn't even throw in the first place, I think.

**Comment by 25huizengek1** [comment]
Please let me know if it worked so we can close the issue.

**Comment by Syntax-Err5** [comment]
Yep it's fixed now, thanks bro
